name: addition
description: A mental addition game.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flame: ^0.10.2
  device_info: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg/background.png
    - assets/images/numbers/black/
    - assets/images/numbers/gray/
    - assets/images/bg/lose.png
    - assets/images/branding/logo.png
    - assets/images/ui/dialog-help.png
    - assets/images/ui/icon-help.png
    - assets/images/ui/start_button.png
    - assets/audio/sfx/up.mp3
    - assets/audio/sfx/down.mp3
